# .github/labeler.yml

# Apply the "frontend" label if changes include files in the "frontend" directory
frontend:
  - 'frontend/**'

# Apply the "backend" label if changes include files in the "backend" directory
backend:
  - 'backend/**'

# Apply the "docs" label if changes include files in the "docs" directory
docs:
  - 'docs/**'

# Apply the "config" label if changes include files in the "config" directory
config:
  - 'config/**'
