name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          args: |
            -Dsonar.projectKey=arianne05_ci-cd-sample-activity
            -Dsonar.organization=arianne05
            -Dsonar.exclusions=**/*.yml
            # Uncomment and adjust the following lines if needed
            # -Dsonar.sources= # optional
            # -Dsonar.tests= # optional
            # -Dsonar.verbose= # optional
          projectBaseDir: .
